---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    code_folding: hide
---
    

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(knitr)
data(instacart)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Bar chart

```{r echo=FALSE}
instacart %>% 
  count(aisle) %>% 
  filter(n > 15000) %>% 
  mutate(
    aisle = factor(aisle),
    aisle = fct_reorder(aisle, n)
  ) %>% 
  plot_ly(
    x = ~aisle, y = ~n, color = ~aisle, 
    type = "bar", colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Aisles"),
    yaxis = list(title = "Number of orders"),
    title = "Aisles (orders > 15,000)"
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Boxplot

```{r}
instacart %>% 
  select(add_to_cart_order, order_number, product_name, aisle, department) %>% 
  filter(aisle == "fresh vegetables") %>%
  filter(product_name %in% c("Organic Cucumber","Organic Zucchini","Organic Yellow Onion","Organic Garlic","Asparagus", "Organic Red Onion", "Yellow Onions", "Broccoli Crown", "Red Peppers", "Fresh Cauliflower")) %>%
  plot_ly(
    y = ~add_to_cart_order,
    x = ~product_name,
    color = ~product_name,
    type = "box",
    colors = "viridis"
  ) %>% 
  layout(
    xaxis = list(title = "product name"),
    yaxis = list(title = "number of cart order"),
    title = "Number of itmes in cart for most 10 popular fresh vegetables"
  ) 
```

### Scatter

```{r}
instacart %>% 
  filter(aisle == "fresh vegetables") %>% 
  filter(product_name %in% c("Organic Cucumber","Organic Zucchini","Organic Yellow Onion","Organic Garlic","Asparagus", "Organic Red Onion", "Yellow Onions", "Broccoli Crown", "Red Peppers", "Fresh Cauliflower")) %>% 
  mutate(text_label = str_c("product:", product_name,"\nNumber in cart:", order_number, "\nOrder-hour: ", order_hour_of_day)) %>%
  plot_ly(
    x = ~order_hour_of_day, y = ~add_to_cart_order, color = ~product_name, text = ~text_label,
    alpha = .3, type = "scatter", mode = "markers", colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Order-placed Hour"),
    yaxis = list(title = "Item Number in Cart"),
    title = "Number of 10 popular vegetables Ordered in Cart vs. Ordered Hour"
  )
```

